Pass props through from HOC
thchia/react-oidc pull request #15
Opened 2019-07-23 23:17 UTC by chriskolenko

WrappedComponent has changed to a React.ComponentType

Fixes #14 

I haven't done much Typescript. Hoping React.ComponentType is correct. 

Output of `yarn build`
```
yarn run v1.17.3
$ rm -rf ./lib && tsc
Done in 2.24s.
```

2019-07-24 00:19 UTC, chriskolenko commented
@thchia I can confirm it's working. All the props are coming through. 

I changed the tests from : <Child /> to Child. Updated the readme. Would you like me to create a CHANGELOG.md? The breaking change makes me sad. This will be a minor version bump correct? 0.4.1-alpha?

2019-07-24 02:07 UTC, thchia commented
Thanks for this! I will take a closer look at it later. Regarding the CHANGELOG, don’t worry about it as I will create that before publishing.

2019-07-24 13:50 UTC, thchia requested changes
Can you add a test case for this change. Feel free to either change the implementation of `Child` or create another component that renders something based on its props. Then you will be able to assert that the props have been passed through using `getByText`.

2019-07-24 13:50 UTC, thchia commented on src/makeAuth/index.tsx
> +  return <Props extends {}>(WrappedComponent: React.ComponentType) => {
I believe this should be:

```suggestion
  return <Props extends {}>(WrappedComponent: React.ComponentType<Props>) => {
```
This means that the component being wrapped expects the same props as those that will be passed to the component returned by this HoC.

2019-07-25 03:02 UTC, chriskolenko commented
Done. First time writing a test in react. Thanks for forcing me.

2019-07-25 14:47 UTC, thchia requested changes
Suggested to change the test case you added to the "happy path", instead checking that the props **are** passed.

I probably won't get back to this till the weekend, but chances are this will be published under `v0.5.0`.

`v0.4.0` never made it to a latest release, and in fact the changes in that release turned out to be untenable. To follow semver strictly, I will release these changes as `0.5.0` (or maybe just finally go to v1).

2019-07-25 14:47 UTC, thchia commented on src/makeAuth/index.test.tsx
> +      getUserFunction: failedGetUser
Let's change this to the `successfulGetUser`.

```suggestion
      getUserFunction: successfulGetUser
```

Currently your test asserts that `'bar'` is **not** present, which is correct if `getUserFunction` fails, but it is also correct if your implementation of passing props is broken, so this test does not strictly check that the passing of props works.

After this, you will need to update line 110. I've made a suggestion there.

2019-07-25 14:47 UTC, thchia commented on src/makeAuth/index.test.tsx
> +    expect(queryByText('bar')).toBeNull()
```suggestion
    getByText('bar')
```

2019-07-25 14:47 UTC, thchia commented on src/makeAuth/index.test.tsx
> +    const { queryByText } = render(<WithAuth foo="bar" />)
```suggestion
    const { getByText } = render(<WithAuth foo="bar" />)
```

2019-07-29 00:07 UTC, chriskolenko commented
All good to merge this sometime today?

2019-07-29 03:06 UTC, thchia commented
Yes! Sorry I didn’t get any notification you’d done the changes.. will merge this in the next few hours.

2019-07-29 07:18 UTC, thchia approved these changes

2019-07-29 07:18 UTC, merged

2019-07-29 07:28 UTC, thchia commented
@chriskolenko [done](https://github.com/thchia/react-oidc/releases/tag/v1.0.0)